### ISSUE TITLE
Can the upper bound on google-api-python-client be removed from this package?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/earthengine-api-feedstock#201]
### Comment:

Many versions of this package have the restriction google-api-python-client <2.  However, based on [this](https://github.com/google/earthengine-api/issues/157) report, it appears that the issue that was causing problems with google-api-python-client >=2 has been fixed since earthengine-api version 0.1.256.

**Comment by bengalin** [comment]
Yes, thank you.  We removed the upper constraint in our GitHub repo in version 0.1.331: https://github.com/google/earthengine-api/commit/fd9374b1fc57a403d6c699276ddf6ea5660f7425#diff-eb8b42d9346d0a5d371facf21a8bfa2d16fb49e213ae7c21f03863accebe0fcf.  Updating conda recipe now.

**Comment by bengalin** [comment]
Just to close the loop, recipe was updated in https://github.com/conda-forge/earthengine-api-feedstock/commit/037948b47354b1855216af90f567fe49895e5507
